### ISSUE TITLE
Lower Cabal requirement to 1.10

### ISSUE THREAD

**Issue by asr** [robdockins/edison#1]
`Cabal-Version:  >= 1.22` is not necessary (see https://github.com/judah/haskeline/issues/17#issuecomment-68946643) but it can generate problems with GHC 7.8.*.

**Comment by asr** [comment]
Thanks!

**Comment by andreasabel** [comment]
Please update also the .cabal file on hackage.  You can do so in the "maintainer's corner" without uploading a new version to hackage.
This way, an unnecessary build failure for Agda can be fixed, see http://matrix.hackage.haskell.org/package/Agda#GHC-7.8/Agda-2.5.1
Thanks!

**Comment by robdockins** [comment]
Unfortunately, cabal version can't be changed from the maintainer's corner.

Nonetheless, it's easy enough to push a fresh package up to Hackage, so I've done that.

**Comment by andreasabel** [comment]
Thanks!
