### ISSUE TITLE
Build error with GHC 8.4.1-alpha1

### ISSUE THREAD

**Issue by asr** [robdockins/edison#11]
GHC 8.4.1-alpha1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2017-December/015235.html). While testing [Agda](https://github.com/agda/agda) with this version of GHC, I got various errors on EdisonCore (master branch) related to missing instances of `Semigroup` like this:

```
$ cabal install
...
src/Data/Edison/Seq/BraunSeq.hs:563:10: error:
    • No instance for (Semigroup (Seq a))
        arising from the superclasses of an instance declaration
      There are instances for similar types:
        instance Semigroup (Data.Sequence.Internal.Seq a)
          -- Defined in ‘Data.Sequence.Internal’
    • In the instance declaration for ‘Monoid (Seq a)’
    |
563 | instance Monoid (Seq a) where
    |          ^^^^^^^^^^^^^^
Failed to install EdisonCore-1.3.1.1
...
```

These errors are reported as warnings in GHC 8.0.2/8.2.2 using the `-Wsemigroup` flag:

```
$ cabal install --force-reinstalls --ghc-options='-Wsemigroup -Werror'
...
src/Data/Edison/Seq/JoinList.hs:437:10: warning: [-Wsemigroup]
    ‘Seq’ is an instance of Monoid but not Semigroup.
    This will become an error in a future release.

<no location info>: error: 
Failing due to -Werror.
```

So, fixing these warnings on GHC 8.0.2/8.2.2 fix the errors on GHC 8.4.1-alpha1.

Blocking https://github.com/agda/agda/issues/2878.

**Comment by robdockins** [comment]
Thanks for the report, I'll grab a bit of time soon to work through these.

**Comment by asr** [comment]
For knowing the warnings in GHC 8.0.2/8.2.2, I realised it's better to use the `-Wcompat` flag:

```
$ cabal install --force-reinstalls --ghc-options='-Wcompat -Werror'
```

**Comment by robdockins** [comment]
I've pushed changes and uploaded a new version of EdisonCore to Hackage (1.3.2) that should fix these errors.  I haven't fetched GHC 8.4, so I don't know if that fixes all you problems.  Please reopen if not.

**Comment by asr** [comment]
EdisonCore 1.3.2 compiled with GHC 8.4.1-alpha1. Thanks for fixing and releasing!
