### ISSUE TITLE
Project edison appears unmaintained

### ISSUE THREAD

**Issue by andreasabel** [robdockins/edison#19]
This project appears to be unmaintained. There hasn't been any visible activity on this repo in 4 years.

The published versions do not build with GHC >= 8.8.  I have made the necessary revisions on hackage to reflect this fact, e.g.: https://hackage.haskell.org/package/EdisonAPI-1.2.2/revisions/

**Comment by robdockins** [comment]
I see that I've let some compatibility fixes go ignored for a bit, I'll deal with that.

**Comment by andreasabel** [comment]
> This library is indeed _very_ on the back burner, as there doesn't appear to be much general interest.

This is unfortunately a self-fulfilling prophecy.  Customers leave (are forced to leave) when a library isn't kept up-to-date with the Haskell ecosystem.  Agda used to depend on Edison, but we dropped the dependency in 2019 when adopting GHC 8.8 (which Edison does not support to this day...).  Background:
- https://github.com/agda/agda/issues/3725
- https://github.com/agda/agda/issues/4110

**Comment by robdockins** [comment]
I've updated EdisonAPI and EdisonCore with the outstanding updates to build on recent GHC, and pushed new versions (1.3.3) to Hackage.

**Comment by robdockins** [comment]
@Lysxia has volunteered to assist and perhaps take over maintenance, so hopefully that will help keep things more responsive.

**Comment by Lysxia** [comment]
I'm happy to keep this library working.
