### ISSUE TITLE
Add version bounds for the imported packages.

### ISSUE THREAD

**Issue by andreasabel** [robdockins/edison#3]
The .cabal file does not contain version bounds for all the imported packages.

**Comment by robdockins** [comment]
I'm not convinced this is a bug to fix.  Are the lack of bounds causing a problem?

**Comment by andreasabel** [comment]
I don't know.  They could. 
https://wiki.haskell.org/Package_versioning_policy
However, as you are only using `mtl`, `containers`, and `array`, maybe you can expect some stability and wait for the first real breakage.
