### ISSUE TITLE
Missing support for GHC 7.6.3

### ISSUE THREAD

**Issue by asr** [robdockins/edison#4]
I couldn't install EdisonCore using GHC 7.6.3:

```
$ cabal unpack EdisonCore
$ cd EdisonCore-1.3.1/
$ cabal sandbox init
$ cabal install
...
[10 of 26] Compiling Data.Edison.Coll.EnumSet ( src/Data/Edison/Coll/EnumSet.hs, dist/dist-sandbox-4d0d8408/build/Data/Edison/Coll/EnumSet.o )

src/Data/Edison/Coll/EnumSet.hs:182:14:
    Not in scope: `finiteBitSize'
Failed to install EdisonCore-1.3.1
```

**Comment by robdockins** [comment]
I'll push a new release to Hackage with this fix soon; but note that you can also solve this problem by pinning Edison to version 1.2.2 for older GHC.  The only real differences in the 1.3 branch so far are for compatibility with GHC 7.10 and associated base libraries.

**Comment by asr** [comment]
Thanks!
