### ISSUE TITLE
Missing CHANGELOG file

### ISSUE THREAD

**Issue by asr** [robdockins/edison#6]
There isn't a CHANGELOG in Hackage.

**Comment by asr** [comment]
Any news about it?

**Comment by robdockins** [comment]
Looks like I just need to add the existing `CHANGES` file to the `extra-source-files` section?  Is that right?

**Comment by asr** [comment]
Right (see https://stackoverflow.com/questions/21076759/how-to-add-a-changelog-to-a-cabal-package) .

**Comment by robdockins** [comment]
The CHANGES file is now included in the `EdisonCore` package

**Comment by asr** [comment]
Thanks!
